### ISSUE TITLE
Can't seem to from pylibrelinkup.client import LibreLinkUpClient

### ISSUE THREAD

**Issue by Carebear80** [robberwick/pylibrelinkup#15]
After pip install pylibrelinkup from anaconda env python 3.11.10
$ python
from pylibrelinkup.client import LibreLinkUpClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'LibreLinkUpClient' from 'pylibrelinkup.client' (/home/machine/anaconda3/envs/libre/lib/python3.11/site-packages/pylibrelinkup/client.py)

Does this require more time?

**Comment by robberwick** [comment]
Hi @Carebear80 

Apologies, the docs were out of date, and reflecting an old version of the API. I'll update those. In the menatime, try the following and let me know how you get on:

```python
from pylibrelinkup.client import Client

client = Client(email='your_username', password='your_password')
client.authenticate()

patient_list = client.get_patients()
print(patient_list)

patient = client.get_patients()[0]
patient_data = client.read(patient_identifier=patient.patient_id)

print(patient_data.current)
print(patient_data.history)
```
